### ISSUE TITLE
Add support for CKEditor

### ISSUE THREAD

**Issue by benthamite** [fregante/GhostText#219]
# Setup

Browser: Chrome Version 96.0.4664.55 (Official Build) (x86_64)
Editor: GNU Emacs 28.0.50 / Sublime Text, Stable Channel, Build 4121

# Description
GhostText works fine on most websites, but it fails on a few that I personally use very often. The foremost example is [LessWrong](https://www.lesswrong.com/). When I trigger GhostText from the browser, it opens a new buffer on Emacs with the text `<p><br data-cke-filler="true"></p>`. However, any text entered at this point is not sent back to the browser; on LessWrong, the comment field remains empty.

I downloaded and installed Sublime text, and can confirm that it exhibits the same behavior.

**Comment by fregante** [comment]
The site uses https://ckeditor.com

PR welcome to add support for it

https://github.com/fregante/GhostText/blob/main/contributing.md#adding-support-for-more-editors

**Comment by fregante** [comment]
CKEditor is a WYSIWYG editor and it can't really be "supported" here because your editor would still need to receive the HTML and not plain text.

You have two options:

- switch to the "plain editor" in CKEditor so that GhostText can interact with the textarea
- Wait for https://github.com/fregante/GhostText/issues/53
