### ISSUE TITLE
Unable to use on CompilerExplorer/godbolt.org (Monaco Editor)

### ISSUE THREAD

**Issue by iamkroot** [fregante/GhostText#283]
Hello! Thanks for this cool extension!
I am unable to use GT with [Compiler Explorer](https://godbolt.org/). It [uses](https://github.com/compiler-explorer/compiler-explorer/blob/main/static/panes/editor.ts) the Monaco editor under the hood (#239).
Upon activating GT, it does detect the textarea, and my editor (sublime) also prints some logs saying it has connected. But no file is opened inside the editor. Any idea why this would be happening?

**Comment by fregante** [comment]
Thanks for the report! It looks like the initialization is failing for some reason. On this line `this.field` is `undefined`

https://github.com/fregante/GhostText/blob/2874463cb1ab184077a7a3b25fe6ad1117bafdcb/source/ghost-text.js#L156

and I think it's because this line throws an error _in their own code:_

https://github.com/fregante/GhostText/blob/2874463cb1ab184077a7a3b25fe6ad1117bafdcb/source/ghost-text.js#L39-L43

<img width="402" alt="Screenshot" src="https://user-images.githubusercontent.com/1402241/235342166-595cb173-be29-4f27-bebf-f299c3d8b963.png">


I think it's their own "Sentry" error reporter.

An easy solution would be to make that `dispatchEvent` call asynchronous so it doesn't affect the constructor. Or better yet wrap it in `try/catch`

However that isn't guarantee to fix it since it's _their_ code that is breaking it. It might be worth contacting https://sentry.io, they might know why _their_ code is throwing an error in a basic `dispatchEvent`
